version: '3.1'
services:                                                                                     

 bookstorre:
    image: mysql
    environment:                                                                              
      MYSQL_ROOT_PASSWORD: frodobolson
    volumes:                                                                                  
      - ./db/:/var/lib/mysql
    ports: 
      - 3306:3306
    healthcheck:                                                                              
      test: ["CMD", "mysqladmin",                                                             
                    "-h",                                                                     
                    "localhost",                                                              
                    "-uroot",
                    "-pximira",                                                               
                    "processlist"]                                                            
      interval: 30s                                                                           
      timeout: 30s                                                                            
      retries: 5 

  

 
                                                                                          


                                                                                              
